# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, default='Ryan', max_length=20, null=True),
        ),
    ]
