# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
